project_id = "koeoboygsssyajpdstel"

[functions.generate-timeline]
verify_jwt = false

[functions.search-images]
verify_jwt = false

[functions.search-images-tol]
verify_jwt = false

[functions.search-youtube]
verify_jwt = false

[functions.search-spotify]
verify_jwt = false

[functions.generate-speech]
verify_jwt = false

[functions.generate-speech-elevenlabs]
verify_jwt = false

[functions.search-freesound]
verify_jwt = false

[functions.generate-song-lyrics]
verify_jwt = false

[functions.generate-suno-track]
verify_jwt = false

[functions.check-suno-status]
verify_jwt = false

[functions.proxy-audio]
verify_jwt = false

[functions.blacklist-image-ddg]
verify_jwt = false

[functions.generate-acestep-track]
verify_jwt = false

[functions.generate-diffrhythm-track]
verify_jwt = false
