project_id = "koeoboygsssyajpdstel"

[functions.generate-timeline]
verify_jwt = false

[functions.search-images]
verify_jwt = false

[functions.search-youtube]
verify_jwt = false

[functions.search-spotify]
verify_jwt = false